---
title: "Assignment04"
author: "Dingyuan Gu"
date: "2024-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r}
library(tidyverse)
```


## 1. Tidy data and iteration 

### 1.1 (Q1)

```{r}
library(purrr)
```


### 1.1 (Q2)

```{r}
impute_by_median<-function(x){
 mu<-median(x,na.rm=TRUE) # first compute the mean of x
 impute_f<-function(z){ # coordinate-wise imputation
 if(is.na(z)){
 return(mu) # if z is na replace with mean
 }else{
 return(z) # otherwise leave in place
 }
 }
return(map_dbl(x,impute_f)) # apply the map function to impute across 
vector
}


v<-c(1,2,NA,4)
impute_by_median(v)
```

### 1.1 (Q3)

```{r}
x_start <- 0
x_end <- 10
x <- seq(from = x_start, to = x_end, by = 0.1)
y <- 5 * x + 1
df_xy <- data.frame(x = x, y = y)

df_xy%>%head(5)
```

### 1.1 (Q4)

```{r}
df_xy %>% mutate(z=map2_dbl(x,y,~.x+.y)) %>% head(5)

sometimes_missing<-function(index,value){
 if(index%%5==0){
   return(NA)
 }else{
   return(value)
  }
 }

sometimes_missing(14,25)
sometimes_missing(15,25)

df_xy_missing <- df_xy %>% mutate(y=map2_dbl(row_number(),y,sometimes_missing))

df_xy_missing %>% head(10) 
```

### 1.1 (Q5)

```{r}
df_xy_imputed <- df_xy_missing %>% mutate(y=impute_by_median(y))
head(df_xy_imputed)
```

### 1.2 (Q1)

```{r}
library(readxl)
folder_path <- "C:\\Users\\levit\\Downloads\\"
file_name <- "HockeyLeague.xlsx"
file_path <- paste(folder_path,file_name,sep="")
wins_data_frame <- read_excel(file_path,sheet="Wins")
wins_data_frame %>% select(1:5)%>% head(3)
```

```{r}
w_l_narrow<-function(w_or_l){ 
return( 
read_excel(file_path,sheet=w_or_l)%>% 
rename(Team=...1)%>%   #第一列命名为Team,原始数据无列名
pivot_longer(!Team,names_to="Year",values_to="val")%>% ##除Team列的其他列, 列名存入Year, 值存入val
mutate(Year=as.integer(Year))%>% 
separate(col=val,into=c(w_or_l,"Total"),sep=" of ",convert=TRUE) 
) 
} 
wins_tidy<-w_l_narrow(w_or_l="Wins") 
wins_tidy %>% dim()
wins_tidy%>%head(5)
```

### 1.2 (Q2)

```{r}
losses_tidy<-w_l_narrow(w_or_l="Losses") 
losses_tidy %>% head(5)
```

### 1.2 (Q3)

```{r}
hockey_df <- inner_join(wins_tidy,losses_tidy)%>%mutate(Draws=Total-Wins-Losses)%>%mutate(Wins_rt=Wins/Total)%>%mutate(Losses_rt=Losses/Total)%>%mutate(Draws_rt=Draws/Total)
hockey_df %>% head(5)

#下面这种写法更优雅

#hockey_df<-inner_join(wins_tidy,losses_tidy)%>%
  #mutate(Draws=Total-Wins-Losses)%>% 
  #mutate(across(starts_with(c("Wins","Losses","Draws")),~.x/Total, .names="{.col}_rt")) 
#hockey_df %>% head(5)
```

### 1.2 (Q4)

```{r}

hockey_df %>%
  select(-Wins,-Draws,-Losses) %>% 
  group_by(Team) %>% 
  summarise(across(c("Wins_rt","Losses_rt","Draws_rt"), 
                   list(md=median,mn=mean), 
                   .names="{substring(.col,1,1)}_{.fn}")) %>% 
  arrange(desc(W_md))
```


### 1.3 (Q1)

```{r}
num_red_balls<-3 
num_blue_balls<-7 
total_draws<-22 
prob_red_spheres<-function(z){ 
  total_balls<-num_red_balls+num_blue_balls 
  log_prob<-log(choose(total_draws,z))+ 
    z*log(num_red_balls/total_balls)+(total_draws-z)*log(num_blue_balls
 /total_balls) 
  return(exp(log_prob)) 
} 
 
num_trials<-1000 # set the number of trials 
set.seed(0) # set the random seed 
 
num_reds_in_simulation <- data.frame(trial=1:num_trials) %>% 
  mutate(sample_balls = map(.x=trial, ~sample(10,22, replace = TRUE))) %>%  
  mutate(num_reds = map_dbl( .x=sample_balls, ~sum(.x<=3) ) ) %>%  
  pull(num_reds)  
 
prob_by_num_reds <- data.frame(num_reds=seq(22)) %>%  
  mutate(TheoreticalProbability=prob_red_spheres(num_reds)) %>% mutate(EstimatedProbability=map_dbl(.x=num_reds,~sum(num_reds_in_simulation==.x))/num_trials) 
```

### 1.3 (Q2)

```{r}
prob_by_num_reds %>%pivot_longer(cols=c("EstimatedProbability","TheoreticalProbability"),names_to="Type",values_to="count") %>% ggplot(aes(num_reds,count)) +  
  geom_line(aes(linetype=Type, color=Type)) + geom_point(aes(color=Type
 )) + scale_linetype_manual(values = c("solid", "dashed"))+ theme_bw() + xlab("Number of reds") + ylab("Probabilities")
```




